# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Annie < Formula
  desc "AI-powered infrastructure observability CLI"
  homepage "https://anyshift.io"
  version "0.8.31"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://annie-cli.anyshift.io/releases/0.8.31/annie-0.8.31-darwin-amd64.tar.gz"
      sha256 "2ccbf19056ba7c0a98131bccc43f3976b8c8935f27132fa2da71bdf7a64e2b88"

      define_method(:install) do
        bin.install "annie"
      end
    end
    if Hardware::CPU.arm?
      url "https://annie-cli.anyshift.io/releases/0.8.31/annie-0.8.31-darwin-arm64.tar.gz"
      sha256 "12960bc5a3d7d73e474bf5b1489f9d4e9ff4551b6ad9a82cd8d0360bc29a434b"

      define_method(:install) do
        bin.install "annie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://annie-cli.anyshift.io/releases/0.8.31/annie-0.8.31-linux-amd64.tar.gz"
      sha256 "1f617af1cca0ef5033c6e509122cb2296059c4b544c9a9066a4091b298e38bb4"
      define_method(:install) do
        bin.install "annie"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://annie-cli.anyshift.io/releases/0.8.31/annie-0.8.31-linux-arm64.tar.gz"
      sha256 "4419f80add7001ed4d9fd2143b91375c01f7761f7121b869fa111d7828274989"
      define_method(:install) do
        bin.install "annie"
      end
    end
  end

  test do
    system "#{bin}/annie", "--version"
  end
end
