# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Annie < Formula
  desc "AI-powered infrastructure observability CLI"
  homepage "https://anyshift.io"
  version "0.8.24"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://annie-cli.anyshift.io/releases/0.8.24/annie-0.8.24-darwin-amd64.tar.gz"
      sha256 "262ce8f2bb1b05e9f882130c8c3a702e99c8c85ca3bdc489afdfd4952698f483"

      define_method(:install) do
        bin.install "annie"
      end
    end
    if Hardware::CPU.arm?
      url "https://annie-cli.anyshift.io/releases/0.8.24/annie-0.8.24-darwin-arm64.tar.gz"
      sha256 "b074efa5677ed3e01e2a15cc3261a884da0667dafa1e109d6b708f2e67ea5bba"

      define_method(:install) do
        bin.install "annie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://annie-cli.anyshift.io/releases/0.8.24/annie-0.8.24-linux-amd64.tar.gz"
      sha256 "c8de9ffec719a822fa2a6ef2082d24452e9ec4049498378839a094420e5b3957"
      define_method(:install) do
        bin.install "annie"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://annie-cli.anyshift.io/releases/0.8.24/annie-0.8.24-linux-arm64.tar.gz"
      sha256 "22ebdf485f3790d9ad14a5fafa9fd8f91cd68583fef7da0cd81d1c092fcf0806"
      define_method(:install) do
        bin.install "annie"
      end
    end
  end

  test do
    system "#{bin}/annie", "--version"
  end
end
